name: CI
on:
  push:
    branches:
      - electron
jobs:
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: install node tools
      run: npm install --global --production windows-build-tools@4.0.0
    - name: install node-gyp
      run: npm install --global node-gyp@latest
    - name: Set node config to use python2.7
      run: npm config set python python2.7
    - name: Set node config to set msvs_version to 2015
      run: npm config set msvs_version 2015
    - name: Work around for Windows Server 2019
      run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
    - name: Install dependencies
      run: yarn install
    - name: check env
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: set
    - name: Build on Windows
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: yarn build
    - name: Build Electron
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: yarn electron:buildWin
    - name: see directory
      run: ls ./electron_dist/squirrel-windows
    - uses: lucyio/upload-to-release@master
      with:
        name: lucyio/electron
        path: ./electron_dist/squirrel-windows
        action: unpublished
        release_id: 0.5.9
        release-repo: lucyio/electron
